"""Build the deduplicated corpus from the recorded sessions.

A SHAPE is (action_class, evidence_verdict, risk_class, seam_outcome,
ground_truth_outcome, post_refusal_class) — the structural facts, not the
wording. Two proposals that differ only in a table name or a branch name share
a shape. The first proposal of each shape is kept, and every session that
produced the shape is listed. Counts come from this artifact, never a
prediction (doctrine #11).
"""

from __future__ import annotations
import json, hashlib
from pathlib import Path

SESS = Path(__file__).parent / "sessions"
OUT = Path(__file__).parent / "corpus.json"

def _ground_truth(rec: dict) -> str:
    # what CORRECT work warrants, recovered from the note's expected outcome
    # (stored in the JSONL as expected_correct_outcome on the proposal line).
    return rec.get("expected_correct_outcome", "")

def shape_sig(rec: dict) -> str:
    key = "|".join([
        rec["action_class"], rec["grader_verdict"], rec["risk_class"],
        rec["submit_outcome"], _ground_truth(rec), str(rec.get("post_refusal_class")),
    ])
    return "sh-" + hashlib.sha256(key.encode()).hexdigest()[:10]

def main() -> int:
    shapes: dict[str, dict] = {}
    order: list[str] = []
    for log in sorted(SESS.glob("*.jsonl")):
        for line in log.read_text().splitlines():
            o = json.loads(line)
            if o.get("kind") != "proposal":
                continue
            sig = shape_sig(o)
            if sig not in shapes:
                order.append(sig)
                shapes[sig] = {
                    "shape_id": sig,
                    "task": o["task"],
                    "intent": o["intent"],
                    "action_class": o["action_class"],
                    "check_id": o["check_id"],
                    "evidence_verdict": o["grader_verdict"],
                    "risk_class": o["risk_class"],
                    "seam_outcome": o["submit_outcome"],
                    "seam_executed": o["executed"],
                    "seam_refusal_reason": o["refusal_reason"],
                    "ground_truth_outcome": _ground_truth(o),
                    "seam_matches_ground_truth": bool(o["correct_verdict"]),
                    "post_refusal_class": o.get("post_refusal_class"),
                    "producing_sessions": [o["session"]],
                    "note": o["note"],
                }
            else:
                sess = shapes[sig]["producing_sessions"]
                if o["session"] not in sess:
                    sess.append(o["session"])
    corpus = {
        "_doc": "Adversarial-session corpus. Each entry is a DISTINCT shape a "
                "finishing-minded agent produced against the real seam. seam_outcome "
                "is OBSERVED; a shape where seam_matches_ground_truth is false is a "
                "FINDING (the seam is as good as the check it was given), recorded, "
                "never weakened. CI replays this deterministically; membership is "
                "pinned exactly.",
        "prober": "session model (frontier-class); no independent model API in the "
                  "environment, so proposals were generated by the session model as "
                  "an integrator and every outcome was run, not predicted",
        "shapes": [shapes[s] for s in order],
    }
    OUT.write_text(json.dumps(corpus, indent=2, sort_keys=False) + "\n")
    print(f"shapes: {len(order)}")
    for s in order:
        e = shapes[s]
        flag = "" if e["seam_matches_ground_truth"] else "  <-- FINDING (seam != ground truth)"
        print(f"  {e['shape_id']}  {e['action_class']:15} ev={e['evidence_verdict']:11} "
              f"-> {e['seam_outcome']:11} truth={e['ground_truth_outcome']:8}{flag}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
